
version: 2

models:
  - name: related_products_info_normalization
    description: "A related-products dbt model"
    columns:
      - name: _id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

