
version: 2

models:
  - name: enquires_dbt_model
    description: "An enquiries dbt model"
    columns:
      - name: _id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

